# Generated by Django 4.1.2 on 2022-11-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'available'), ('booked', 'booked'), ('rented', 'rented'), ('damaged', 'damaged')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
